### ISSUE TITLE
description of single quoting behaviour seems wrong

### ISSUE THREAD

**Issue by wbolster** [anordal/shellharden#14]
the document currently contains:

> The simplest is to go for single quotes, since these have the simplest escaping rules – only one: ' → '\''.

this seems incorrect. backslashes do _not_ escape anything inside single quotes::

```$ echo '\'
\
```

that also means that this is an incomplete command, as can be seen from the continuation prompt:

```
$ echo '\''
> 
> ^C
```

the correct approach is to replace `'` with `'"'"'` which looks horrible, but is correct:

- `'` closes the open single-quoted string
- `"` opens a double-quoted string
- `'` puts a single quote inside the double-quoted string
- `"` closes the double-quoted string
- `'` opens a new single-quoted string

**Comment by anordal** [comment]
You have to actually quote the string as well. Example:

    echo 'Don'\''t stop (12" dub mix).mp3'

So I'm actually proposing the same as you, exept using `'\''` instead of `'"'"'`. Agree?

I guess I should have added an example. Any other way I could make it clearer?

**Comment by wbolster** [comment]
aaaah, now i see.

![image](https://user-images.githubusercontent.com/748944/40375571-3fd56498-5dec-11e8-9e07-1fcc72d573be.png)

somehow i totally missed the single quotes in the replacement string while reading this. sorry about that.

i guess an example would help, yeah.
