### ISSUE TITLE
Does not consider default values.

### ISSUE THREAD

**Issue by apeschel** [anordal/shellharden#16]
Shellharden does not consider the quotes in a default value, which can lead to odd recommendations. There doesn't seem to be any actual problem with the suggestion though, other than looking odd.

Given:

```
#!/usr/bin/env bash

echo ${bar:-"two words"}
```

Shellharden produces:

```
#!/usr/bin/env bash

echo "${bar:-"two words"}"
```

The expected output should probably be as follows:

```
#!/usr/bin/env bash

echo "${bar:-two words}"
```

**Comment by anordal** [comment]
I must admit I haven't used this feature much. Why would it be bad to quote the default value?

I couldn't see that it made a difference for the particular example, but here it did:

    echo "${bar:-"two{}words"}"

Not that I've ever encountered that. Shellharden emits a parse error.

**Comment by apeschel** [comment]
@anordal Looks like you're right -- it looks a bit odd with how the quotes match up, but the default value should be quoted as well. This is an unusual edge case that I'll have to remember for the future.
