### ISSUE TITLE
Splitting strings into arrays

### ISSUE THREAD

**Issue by ulrikrasmussen** [anordal/shellharden#18]
Thank you for taking the time to write "Safe ways to do things in bash", this is extremely valuable information. I stumbled upon a surprising behavior in one of your suggestions.

The `read`-based method for splitting strings into arrays [described here](https://github.com/anordal/shellharden/blob/master/how_to_do_things_safely_in_bash.md#those-exceptional-cases-where-you-actually-intend-to-split-the-string) breaks in combination with `set -e`, since the return code of `read` is nonzero when it encounters end-of-file. I am not sure if I have a good suggestion for how to fix it, short of specifying a long unique string for the `-d` argument and appending it to the end of the `printf` format string, or putting the call to `read` within a compound expression.

Tested on Bash 4.4.19.

**Comment by anordal** [comment]
Thanks for reporting this!

A common workaround to get things working with `set -e` is to add `|| true` to the end of the command. That worked.
