### ISSUE TITLE
Doesn't build on Windows

### ISSUE THREAD

**Issue by Amomum** [anordal/shellharden#19]
I cloned current master and did `cargo build`. Got this:
```
Compiling shellharden v3.1.0 (file:///H:/GitLocalRepos/shellharden)
error: expected item, found `..`
 --> src\main.rs:1:1
  |
1 | ../shellharden.rs
  | ^^ expected item

error: aborting due to previous error

error: Could not compile `shellharden`.

To learn more, run the command again with --verbose.
```

I'm using 
```
stable-i686-pc-windows-gnu (default)
rustc 1.26.1 (827013a31 2018-05-25)
```

What am I doing wrong?

**Comment by anordal** [comment]
So the symlink gets checked out as a regular file on Windows. That's what I feared. Thanks for letting me know!

Just move shellharden.rs to src/main.rs, replacing that file.

I was going to keep that symlink for one release for the transition to Cargo (#9).

**Comment by Amomum** [comment]
That worked, thanks!

**Comment by anordal** [comment]
This needs fixing.
