### ISSUE TITLE
Incorrect assumption at how_to_do_things_safely_in_bash.md +320

### ISSUE THREAD

**Issue by mrinaldhillon** [anordal/shellharden#24]
Following seems incorrect since command's return value is overwritten by if statement.
if ! command; then
      echo "Command returned $?"
fi

Use following instead:
command || echo "Command returned $?"

**Comment by anordal** [comment]
Well spotted sir!

I think the negation is enough to explain this:

    > ! bash -c "exit 42"
    > echo "$?"
    0
