### ISSUE TITLE
An argument for preferring curly braces

### ISSUE THREAD

**Issue by westurner** [anordal/shellharden#3]
In reply to https://github.com/anordal/shellharden/blob/master/how_to_do_things_safely_in_bash.md#should-i-use-curly-braces :

> Correct: ``some_command "${arg1}" "${arg2}" "${arg3}"``
> Better: ``some_command "$arg1" "$arg2" "$arg3"``

Curly braces should be preferred in order to limit the risk that a variable named a prefix of other variables does not alter other variables. An example:

```bash
arg="example"
some_command "$arg1" "$arg2" "$arg3"
some_command "${arg1}" "${arg2}" "${arg3}"
```

**Comment by westurner** [comment]
https://google.github.io/styleguide/shell.xml#Variable_expansion

**Comment by westurner** [comment]
https://news.ycombinator.com/item?id=17069434 and the subsequent comments list a few more reasons:

- there's less noise in word-diffs if it's curly-braced in the first place
- it's easier to identify braced variable names at a glance

**Comment by xyproto** [comment]
As a counter-argument to the second bullet point, it's easier to spot expansion of bash variables and other non-straightforward-use of variables (like `${pkgver%%.0}`) if the use of curly brackets is reserved for those instances, and not for normal usage of variables (like `"$pkgver"`).

**Comment by anordal** [comment]
Where is the risk?

The expansion of "$arg1" does not care if a variable named *arg* exists.

**Comment by westurner** [comment]
My mistake.
