### ISSUE TITLE
Allow unquoted arguments to local et al

### ISSUE THREAD

**Issue by pbrisbin** [anordal/shellharden#30]
I've grown accustom to not quoting the right hand side of variable assignments,

```sh
var=$othervar
var=$(subshell)
var=value
```

This is perfectly safe in all POSIX shells (AFAIK). [Reference](https://unix.stackexchange.com/questions/68694/when-is-double-quoting-necessary).

Shellharden adds quotes to all of these. Do you consider this a bug?

**Comment by anordal** [comment]
You must be an early adopter. Try upgrading.

This feature (57214: Allow unquoted rvalues) was part of the v4.1 release.

I define a bug as a deviation from documentation, so this was a missing feature.

**Comment by pbrisbin** [comment]
Ah, I apologize, I'm not sure what I was looking at. I ran into this in the context of [Restyled](https://restyled.io), where it restyled some extra quotes on me and claimed it was `shellharden` that did it. I just checked directly and (of course), you're right:

```console
% docker run -it --rm restyled/restyler-shellharden:v4.1.1-2 sh
/code # shellharden '' <<'EOM'
> foo=$bar
> baz=bat
> bip=im\ bop
> EOM
foo=$bar
baz=bat
bip=im\ bop
/code #
```

I'm not sure what was going on in that PR, but I'll just have to investigate some other cause next time I see it. Sorry for the noise.

**Comment by pbrisbin** [comment]
Oh wait, I found it! I think it may still be a bug:

```console
/code # shellharden '' <<'EOM'
> local foo=$1
> EOM
local foo="$1"
/code # shellharden --version
4.1.1
```

The `local` seems to be throwing it off.

**Comment by anordal** [comment]
Thank you!

What's going on here is that `local` is a command. It is not (exactly the same as) an assignment, neigher syntactically (consider multiple arguments) nor when it comes to errexit's influence on command substitutions.

Thus why I recommend to [separate the declaration from the assignment](https://github.com/anordal/shellharden/blob/master/how_to_do_things_safely_in_bash.md#gotcha-errexit-is-ignored-in-command-arguments), at least with command substitutions.

But I must admit that `local foo=$1` is legit, useful, and worth supporting.

**Comment by pbrisbin** [comment]
> Thus why I recommend to separate the declaration from the assignment, at least with command substitutions.

That's exactly what ShellCheck says to do as well, but *only* with command substitution -- so I tend to assign right in the declaration otherwise.

Thanks for re-opening!
