### ISSUE TITLE
Don't convert curly quotes in comments?

### ISSUE THREAD

**Issue by richb-hanover** [anordal/shellharden#44]
I have a script that (for some reason) wound up with curly quotes within some documentation comments. e.g.,

```
# “H” and “host” DNS or IP address of the netperf server host (default: netperf.bufferbloat.net)
```
shellharden appears to change these to ^D characters. Is this intended? 

Thanks for a cool tool! 

PS I could believe that I mis-diagnosed. And I am happy to get rid of the curly quotes...

**Comment by anordal** [comment]
That isn't something shellharden does. It must be your terminal. Check if you see the same with other programs, such as `cat` or `less`.

Those quotes look like fine unicode to me (utf-8 octets e2809c and e2809d, as you can see in `xxd`). I wouldn't worry about those.

**Comment by richb-hanover** [comment]
Yes. You are right - I don't know exactly what was causing the problem, but this was PEBCAK (Problem Exists Between Chair and Keyboard :-)
