### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by xyproto** [anordal/shellharden#5]
Please add a `LICENSE` or `COPYING` file, for making `shellharden` easier to package for Linux distros.

Cheers!

**Comment by xyproto** [comment]
ref pull request #7

**Comment by anordal** [comment]
I've been meaning to release it under [MPL 2.0](https://www.mozilla.org/en-US/MPL/2.0/).

**Comment by anordal** [comment]
Fixed in commit bfd12fbca
