### ISSUE TITLE
RELEASES: 4.1.2, 4.1.3, 4.2.0 missing?

### ISSUE THREAD

**Issue by HenrikBengtsson** [anordal/shellharden#51]
Version 4.1.1 is the most recent release according to https://github.com/anordal/shellharden/releases, but looking at the https://github.com/anordal/shellharden/tags, it looks like there are also 4.1.2, 4.1.3, and 4.2.0?

Is it an oversight that those versions are not "released"?

**Comment by anordal** [comment]
That indeed looks confusing. It's just that I uploaded binaries for 4.1.1. So it isn't more "released" than the other tags. I stopped doing that as I haven't been able to test on ARM lately (I fried my Raspberry Pi on a low quality DC converter that overheated and failed open).

**Comment by anordal** [comment]
I deleted the 4.1.1 "release".

**Comment by HenrikBengtsson** [comment]
I see. You might also wanna remove:

"For convenience, a few precompiled binaries are also available in the releases."

from the README. That's what led be to think this might have been a mistake.

PS, maybe it's possible to cross compile view GitHub Actions).
