### ISSUE TITLE
Why not use Cargo?

### ISSUE THREAD

**Issue by kimond** [anordal/shellharden#9]
I was wondering why you didn't use Cargo. Is it a matter of choice or it is because you're not comfortable with it?

Furthermore, using Cargo will allow you to publish your project on [Crates.io](https://crates.io/) and setup a test suite more easily.

**Comment by anordal** [comment]
I'm a bit skeptical to Cargo, tbh.

* Putting my email in the build file, whether that be my sacrificial email (that I also use in git and haven't read in 20 years) or the one I actually use. I'm not comfortable with either.
* In-tree builds wtf?
* My understanding is that Meson's submodules are more flexible than Cargo's dependencies. I might want to use a command line parser lib I wrote in C.

That said, splitting shellharden.rs into multiple files, each with its own unittest, is something I've wanted  to do. I've just postponed the choice between Meson and Cargo.

**Comment by anordal** [comment]
Question: I see why it would make sense to publish a library to Crates.io, but why publish a program there?

**Comment by vi** [comment]
Also got stopped by it:

```
$ cargo install shellharden
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: could not find `shellharden` in registry `https://github.com/rust-lang/crates.io-index`

$ cargo install --git https://github.com/anordal/shellharden
    Updating git repository `https://github.com/anordal/shellharden`
error: Could not find Cargo.toml in `/home/rust/.cargo/git/checkouts/shellharden-a7fdc4ed8a1b7ee3/7f67ebe`
```

**Comment by anordal** [comment]
> cargo install shellharden

Yeah, I learnt something today.

Commt 4743a59 enables that and building with cargo. The old build command `rustc shellharden.rs` will work until next release.

**Comment by kimond** [comment]
@anordal  I'm happy to have been able to make you learn something new about Cargo  :smiley:
